### ISSUE TITLE
Creating a new App

### ISSUE THREAD

**Issue by anas3636** [RecastAI/Recast.AI#1]
Hello,

I'am trying to create a new app using the getting started doc : https://man.recast.ai/?javascript#getting-started
But the link https://recast.ai/new is not working

Thank you for your answer :)

**Comment by PaulRenvoise** [comment]
Hi!

Looks like you were still in the waiting list.
I just activated your account, you should be able to continue the getting started :)

Have fun!

**Comment by anas3636** [comment]
Thank you so much :+1: !
