### ISSUE TITLE
Ways to upload expressions without entity auto extraction

### ISSUE THREAD

**Issue by labdmitriy** [RecastAI/Recast.AI#10]
Hello,

Is it possible to create expressions without entity auto extraction, e.g. using any parameter while creating expressions? Now we don't need entities (but we will use it maybe later), and it seems that turning off entity extraction will speed up the process of creating new expressions.

Thank you.

**Comment by PaulRenvoise** [comment]
Hey,

The entity extraction is used later in the classification pipeline to help categorize intents, so we did not plan to allow skipping it. But the usecase is pretty clear so I'll bring it up for discussion with the team.

**Comment by labdmitriy** [comment]
Hi Paul,

Thank you for response.
