### ISSUE TITLE
Screen goes blank when I write on chat window.

### ISSUE THREAD

**Issue by SofiaPe** [RecastAI/Recast.AI#100]
I want to chat with my bot on train mode but when I put in the first word the screen goes blank. This happened to me a few weeks ago. It was a bug. You can see my last report on the issue here: https://github.com/RecastAI/Recast.AI/issues/90#issue-371225330

![paso1](https://user-images.githubusercontent.com/44376168/47725596-d417d600-dc26-11e8-9405-464e5aa2af9b.PNG)

![blank](https://user-images.githubusercontent.com/44376168/47725581-d1b57c00-dc26-11e8-88f8-dc076a66cb95.PNG)

**Comment by aurelie-lamy** [comment]
Hi @SofiaPe we just fixed it ! try again ;)

**Comment by aurelie-lamy** [comment]
and don't forget to refresh your page

**Comment by SofiaPe** [comment]
Hi @aurelie-lamy its working now, thanks!

**Comment by aurelie-lamy** [comment]
my pleasure!
