### ISSUE TITLE
Can i use the conversation language in webhook url?

### ISSUE THREAD

**Issue by tiulimg** [RecastAI/Recast.AI#104]
because i need to know in which language to respond in the backend server..

**Comment by tiulimg** [comment]
because i need to know in which language to respond in the backend server..

**Comment by dbousque** [comment]
In the body sent to your backend server, you have the language used for the conversation in `nlp.processing_language`, take a look at the Body configuration part here : https://recast.ai/docs/concepts/code-and-webhook

**Comment by tiulimg** [comment]
that is, if I don't use a custom body. or a GET request (to get information from my backend, instead of modifying or posting content to it). 
If I do use one of the following, how can i use the conversation language?

**Comment by dbousque** [comment]
Then, you can send them by putting them in the body of the request, like so for example :
```
{
  "conversation_language": "{{ language }}"
}
```

**Comment by tiulimg** [comment]
GET request can't contain body in recast..

**Comment by tiulimg** [comment]
then I get "Url is not valid". 
![image](https://user-images.githubusercontent.com/43069911/48553039-1efe4280-e8e3-11e8-8463-cd5986bb9448.png)
![image](https://user-images.githubusercontent.com/43069911/48552985-f118fe00-e8e2-11e8-840f-639904bc323f.png)

**Comment by dbousque** [comment]
For some reason, we are not allowed to access other variables than the memory in query params, so what you can do is the following :

<img width="868" alt="query_param" src="https://user-images.githubusercontent.com/16238354/48554060-aba60200-e8dd-11e8-8c60-394acc704458.png">

**Comment by tiulimg** [comment]
Yes, seems it will work. Maybe it could be a feature request also, to access conversation variables from query params.
