### ISSUE TITLE
Chat Bot Not Responding SAP Jam

### ISSUE THREAD

**Issue by Vinay0291** [RecastAI/Recast.AI#107]
Hi Team,

This is in regards with the issue we are facing in accessing our bot via SAP Jam.

We integrated one of our chat bot with SAP Jam but suddenly bot stopped responding to the messages, when we checked with the issue we found that Push notification was running into error and we need to turn off and again turn on notification to make the bot work again. 

We raised OSS ticket for the same to SAP, after analysing the issue they responded saying 

“The Chatbot response problem in the demo happens only when we ping any text besides the standard ones like- "hi", "hey", "hello", "bye" etc.

For example, if I type a random string like "abcde", all your three Chabot fail to respond to it and get stuck, with the Push Notification error message - "Message type non-supported by SAP Jam".
This is up to the design of the bot and not a bug in Jam. And, the error message "Message type non-supported by SAP Jam" implies the bot is trying to respond with a format that Jam does not support. The message types currently supported by Jam are Text, QuickReplies, Card, Carousel, and List.”

We also had call with them in which they asked us to connect with you guys as this issue is from the Recast side, recast sending unsupported format to SAP Jam.

Could you please help us in resolving this issue, if user enters text beyond the required one then Recast should respond with error message in format which is supported by SAP Jam.

Regards,
Vinay

**Comment by aurelie-lamy** [comment]
(card created : SAPMLCONV-972)

**Comment by Vinay0291** [comment]
Any update on the issue ?

**Comment by Vinay0291** [comment]
Is the card accessible to me ? If yes, could you please share the link for it.

Thanks

**Comment by Vinay0291** [comment]
Hi @aurelie-lamy Thanks for the update.

Could you please provide an update on the issue, what's the status and how long will it take to get it resolved.

Thanks in advance.

**Comment by aurelie-lamy** [comment]
Hi @Vinay0291 , our team will work on it on january, so it will be fixed in production on february

**Comment by aurelie-lamy** [comment]
Hi @Vinay0291 

As we already are in touch by mail, I close this conversation :)

Aurélie

**Comment by Vinay0291** [comment]
Hi Aurélie,

Any update on the status ?

When can we expect this issue to be resolved ?

Regards,

Vinay
