### ISSUE TITLE
Links and/or emails on webchat channel

### ISSUE THREAD

**Issue by SofiaPe** [RecastAI/Recast.AI#112]
Hi,
I am sending the user simple message responses with an email on the text using the webchat channel. It would be great if the email link could be underlined, colored, etc or if it allowed clicking on it to redirect the user directly to a "send email" option. 

![1](https://user-images.githubusercontent.com/44376168/49032718-4f639d80-f17b-11e8-9495-56a51b4e7e1b.PNG)

What I need is something like the links Skype por enterprises supports:

![capture](https://user-images.githubusercontent.com/44376168/49032729-55f21500-f17b-11e8-908f-142b80903d2a.PNG)

Thanks!

**Comment by dbousque** [comment]
Hi @SofiaPe, if you want custom behavior, you can fork the webchat and develop additional features :) https://github.com/RecastAI/Webchat
