### ISSUE TITLE
No changes when doing PUT on an expression with modified Token

### ISSUE THREAD

**Issue by TyMarc** [RecastAI/Recast.AI#12]
Looking at the documentation, when we create an expression, we can retrieve the id of it and the tokens we want to modify and create a PUT request on  /expression/${EXPRESSION_ID} to modify the tokens, but if I modify the 'slug' of the word of the token, it doesn't actually get updated.

**Comment by PaulRenvoise** [comment]
Hi TyMarc,

Any slug on any resource is read-only, they're generated using the name field and allows pretty urls to be displayed. Moreover, words a a read-only resource, so that's why you can not update them.

Paul

**Comment by TyMarc** [comment]
Thanks for the quick response. That means that the only way to change the slug of a word in an expression is through the web interface?
