### ISSUE TITLE
webchat in local

### ISSUE THREAD

**Issue by I329189** [RecastAI/Recast.AI#121]
I tried to clone the webchat code and run it on local. It shows "Waiting for changes" and doesnt start. 

Can anyone please help with this?

Thank you

**Comment by OlivierNguyen** [comment]
When you run `npm run start`, it will create a `/dist/webchat.js` file.
To test it, you need to create an `index.html` in the root of your project and add this:

```html
<script src="/dist/webchat.js"
channelId="YOUR_CHANNEL_ID"
token="YOUR_TOKEN"
id="recast-webchat"
></script>
```
