### ISSUE TITLE
message is logged as sent but isn't sent

### ISSUE THREAD

**Issue by tiulimg** [RecastAI/Recast.AI#135]
I have a bug in one of my skills, where when i fill a requirement, the message of the next requirement (or the action's message) isn't sent, even though it's logged as sent...
![image](https://user-images.githubusercontent.com/43069911/51502998-5c9ab280-1de1-11e9-8a4b-304cdc26cf69.png)

**Comment by aurelie-lamy** [comment]
Hi @tiulimg 

do you still have the issue?
if yes, have you click on the yellow i to have more information?

regards,

**Comment by zanzamer** [comment]
No.. unfortunately I can't remember what caused this, but made some changes and it didn't appear again yet.

**Comment by tiulimg** [comment]
No.. unfortunately I can't remember what caused this, but made some changes and it didn't appear again yet.

**Comment by aurelie-lamy** [comment]
ok so I close this one.
