### ISSUE TITLE
another bug where incorrect skill is triggered

### ISSUE THREAD

**Issue by tiulimg** [RecastAI/Recast.AI#136]
I have 2 skills which might use the intent "end" to fill a list of items. hike names or hitchhikers names. 
I use a memory variable in the skill's trigger to differentiate the next skill to trigger ("stage"). While flowing through the initial skills flow yeilds a suitable skill selection (and response), after activating the first skill and then clearing the memory, when I reach the stage of the first skill again it chooses the second skill instead of the first skill because both share an optional requirement even though the second skill doesn't fit the trigger of "stage" memory variable. 

1. first skill triggers:
![image](https://user-images.githubusercontent.com/43069911/51503226-93bd9380-1de2-11e9-8025-2f50af84040b.png)

2. second skill triggers:
![image](https://user-images.githubusercontent.com/43069911/51503247-a59f3680-1de2-11e9-8f7d-dc33754596b8.png)

3. first skill requirements:
![image](https://user-images.githubusercontent.com/43069911/51503372-5574a400-1de3-11e9-8de4-8e2e2da2d396.png)

4. second skill requirements:
![image](https://user-images.githubusercontent.com/43069911/51503340-31b15e00-1de3-11e9-98a3-4201ac8bf422.png)

5. flow:
5.1. some skills a,b,c, c sets "stage" to registertohikes_selecthikes
5.2. skill selecthikes triggers, execute an action and goto selecthikes (without waiting for user input), then it finishes gracefully with @end intent.
5.3. some skills d,e,f, f sets "stage" to registertohikes_friendsdetails
5.4. another bug i guess causes friendsdetails skill not to respond (even it logged as responding, posted another issue a minute ago)
5.5. user inputs and skill g resets memory
5.6. some skills a,b,c, c sets "stage" to registertohikes_selecthikes
5.7. skill selecthikes triggers, execute an action and goto selecthikes (without waiting for user input), but then when @end intent is detected, frienddetails skill is triggered and not selecthikes even that "stage" is still registertohikes_selecthikes, and both have a trigger that checks this memory variable..

6. print screen of bug, friendsdetails skill is triggered and not selecthikes..
![image](https://user-images.githubusercontent.com/43069911/51503532-2dd20b80-1de4-11e9-8eed-88b7e39a75a8.png)

7. selecthikes action if @end is absent
![image](https://user-images.githubusercontent.com/43069911/51503941-bb165f80-1de6-11e9-99f2-7ed8eca71ab8.png)

8. selecthikes action if @end is present
![image](https://user-images.githubusercontent.com/43069911/51503955-cc5f6c00-1de6-11e9-88c1-c30192f07a14.png)

**Comment by aurelie-lamy** [comment]
Hi @tiulimg 

do you still have the issue?

Thanks

**Comment by aurelie-lamy** [comment]
Hi @tiulimg 

Any update ? :)

Thanks and have a nice day!

Aurélie

**Comment by tiulimg** [comment]
Hi, no.. I configured things otherwise and the issue had been resolved

**Comment by aurelie-lamy** [comment]
ok thanks, so I close the issue.

Regards,

Aurélie
