### ISSUE TITLE
Email 

### ISSUE THREAD

**Issue by shahi-hackjack** [RecastAI/Recast.AI#14]
I am trying to get email from user !!Vut I dont get text of email on the webhook  side as type is email not text (sent by recast ) .But i want to know what user has entered in email . so that I can integrate its email to other api's .

**Comment by PaulRenvoise** [comment]
Hi there,
Can you give me more details about the issue? An exemple (with screenshot if you can) would be welcome!

**Comment by shahi-hackjack** [comment]
So basically I am using Rest Api and using Java at backend .So genreally when  I enter some text i get to c text in Java file using 
JsonObject message =jsonObjectMessage.body().getJsonObject("message").getJsonObject("attachment")
so in attachment if the type of message is text i get string input but whereas if input is email the content 
will response with length and type email ...not the actual email text , 

For example if I enter "hello" from telegram i get "hello" in content but whereas if I enter "abc@gmail.com" I get length and type not the  actual email string "abc@gmail.com" .

I think I am clear now ??

**Comment by PaulRenvoise** [comment]
Perfect, we'll open a ticket internally in look into it in the next days. Thanks for your explanation
