### ISSUE TITLE
Training Analytics - Benchmark not runnig

### ISSUE THREAD

**Issue by SofiaPe** [RecastAI/Recast.AI#140]
Hello, I've been trying to run a benchmark for two different bots since last week but the charged porcentage wont go over 0%. I have tried several times for each and even left it running over the weekend to see if time could help, but it still doesn´t work.

![image](https://user-images.githubusercontent.com/44376168/52564179-796b4a00-2dd1-11e9-88e0-b2dc62e5930f.png)

Thanks for the help!

**Comment by aurelie-lamy** [comment]
Hi @SofiaPe 

Do you still have the issue ? If yes, could you please add me to your bot?

Thanks,

**Comment by SofiaPe** [comment]
This is working fine now.
