### ISSUE TITLE
Bug: training deleted after training analysis update was launched

### ISSUE THREAD

**Issue by SofiaPe** [RecastAI/Recast.AI#141]
Hello, I was working on my bot today when the training analytics update was launched. Right after that, it stoped understanding some of the expression I hade trained many moths ago. They are simple expressions like hello, goodbye, yes or no. I tried retraining it but it is still not working. (It's an spanish bot)

I really need to solve this problem as soon as possible since the hole performance of my bot depends on it and its online for the public already. 

Also, I am working with an enterprise account and my bot is built on different envirements, some are working just fine, the newest ones are not.

Thanks for the help!

**Comment by aurelie-lamy** [comment]
Hi @SofiaPe 

we are investigating this issue (SAPMLCONV-1657)

Best,

**Comment by aurelie-lamy** [comment]
Hi @SofiaPe 

We deployed a fix yesterday, could you train your bot again and confirm everything works well?

Thank you,

Aurélie

**Comment by aurelie-lamy** [comment]
Hi @SofiaPe 

any update ? :)

Thank you

Aurélie

**Comment by SofiaPe** [comment]
It's working fine now, thanks.

**Comment by aurelie-lamy** [comment]
Thanks for you reply!

Have a nice day,

Aurélie
