### ISSUE TITLE
long texts appear as empty in test your bot

### ISSUE THREAD

**Issue by tiulimg** [RecastAI/Recast.AI#143]
![image](https://user-images.githubusercontent.com/43069911/53357245-1c75a500-3936-11e9-8f40-7820cb7059aa.png)

**Comment by aurelie-lamy** [comment]
Hi @tiulimg 

could you add me to your bot please (aurelie-nesty) and send me the sentence you wrote?

**Comment by tiulimg** [comment]
done.
in action "comewithcar" in requirements. 
I've found now that those messages in requirements went empty, but on kik connected to that chatbot i do receive that texts. 
![image](https://user-images.githubusercontent.com/43069911/53369438-e2b39700-3953-11e9-8f72-5e2f01bfcea9.png)

Iv'e deleted the texts in hebrew and reentered them and they seem as empty again. But when I edit them I do see the texts, so I guess it's related to the markdown (last feature you've added) and when those sentences begin with 1. 2. 3. 4. 5. or * or something like a list of rules (this is what it is) it appears empty. 
Didn't touch the english texts. It's not related to text's length

**Comment by aurelie-lamy** [comment]
Hi @tiulimg 

We rolled back the markdown feature, do you still have your issue?

Many thanks,

Aurélie

**Comment by tiulimg** [comment]
after refreshing - no.

**Comment by aurelie-lamy** [comment]
ok thanks, so it was due to this feature.
I close the issue :)
