### ISSUE TITLE
POST issue in /gazettes

### ISSUE THREAD

**Issue by kazimanzurrashid** [RecastAI/Recast.AI#15]
When creating a gazette right after creating an entity throws http 400 with a message "Entity is not present in the bot".

I have created an entity with the payload:

`{name: "INFO-REPORT"}` 

And it returns me the following response:

`{"results":{"id":5072,"name":"INFO-REPORT","slug":"info-report","color":"#29b6f6","custom":true,"count":1},"message":"Entity created with success"}`

Then I tried to create a gazette with the following:

`{entity_id: "info-report", is_open: true}`

which throws http 400 with the following response:

`{"results":null,"message":"Entity is not present in the bot"}`

It seems it requires a certain delay between creating an entity and a gazette based on it?

**Comment by ftriquet** [comment]
Hi @kazimanzurrashid 
The problem was that we expected you to have this entity in one of your expressions.
We removed this check as it is quite constraining so you should be able to create a gazette with any custom entity now.
Let me know if it's ok for you before I close the issue.

**Comment by PaulRenvoise** [comment]
Closed for inactivity
