### ISSUE TITLE
CORS HTTP OPTIONS method with Access-Control-Max-Age

### ISSUE THREAD

**Issue by kazimanzurrashid** [RecastAI/Recast.AI#16]
Please add Access-Control-Max-Age:86400 header with  to all your HTTP OPTIONS method otherwise there is an unnecessary delay(250+ ms) when using the api from the browser.

**Comment by JulienBlancher** [comment]
Good catch! You can expect to have it available by the end of the week.

**Comment by PaulRenvoise** [comment]
Fixed in latest release! Thanks for the report :)

![2017-09-17-190444_1757x822_scrot](https://user-images.githubusercontent.com/6033299/30523085-1bf64fac-9bdb-11e7-8604-8480a3b20bb1.png)
