### ISSUE TITLE
bulk creating expressions not working

### ISSUE THREAD

**Issue by kazimanzurrashid** [RecastAI/Recast.AI#19]
I am trying to create bulk expressions, with the following payload, but it always throws an error "Word parameter is invalid", but i am not exactly sure what is wrong with the word, I started with only word name then ended up with all the values of word attribute(e.g slug, auto generated uuid) still no luck:

`{
  "expressions": [
    {
      "source": "wake me up tomorrow 6:30 am with Pull me Under of Dream Theater",
      "language": {
        "isocode": "en"
      },
      "tokens": [
        {
          "space": true,
          "word": {
            "id": "4be6f720-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "wake",
            "slug": "wake"
          },
          "entity": null
        },
        {
          "space": true,
          "word": {
            "id": "4be6f721-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "me",
            "slug": "me"
          },
          "entity": null
        },
        {
          "space": true,
          "word": {
            "id": "4be6f722-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "up",
            "slug": "up"
          },
          "entity": null
        },
        {
          "space": true,
          "word": {
            "id": "4be6f723-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "tomorrow",
            "slug": "tomorrow"
          },
          "entity": {
            "id": "391ada15-580c-5baa-b16f-eeb35d9b1122",
            "slug": "datetime",
            "custom": false
          }
        },
        {
          "space": true,
          "word": {
            "id": "4be6f724-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "6:30",
            "slug": "6-30-99"
          },
          "entity": {
            "id": "391ada15-580c-5baa-b16f-eeb35d9b1122",
            "slug": "datetime",
            "custom": false
          }
        },
        {
          "space": true,
          "word": {
            "id": "4be6f725-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "am",
            "slug": "am"
          },
          "entity": {
            "id": "391ada15-580c-5baa-b16f-eeb35d9b1122",
            "slug": "datetime",
            "custom": false
          }
        },
        {
          "space": true,
          "word": {
            "id": "4be6f726-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "with",
            "slug": "with"
          },
          "entity": null
        },
        {
          "space": true,
          "word": {
            "id": "4be6f727-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "Pull",
            "slug": "pull"
          },
          "entity": {
            "id": "6aa1d07d-df3a-51c5-ae40-4afec0397254",
            "name": "SONG",
            "slug": "song",
            "color": "#ffeb3b",
            "custom": true,
            "count": 1
          }
        },
        {
          "space": true,
          "word": {
            "id": "4be6f728-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "me",
            "slug": "me"
          },
          "entity": {
            "id": "6aa1d07d-df3a-51c5-ae40-4afec0397254",
            "name": "SONG",
            "slug": "song",
            "color": "#ffeb3b",
            "custom": true,
            "count": 1
          }
        },
        {
          "space": true,
          "word": {
            "id": "4be6f729-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "Under",
            "slug": "under"
          },
          "entity": {
            "id": "6aa1d07d-df3a-51c5-ae40-4afec0397254",
            "name": "SONG",
            "slug": "song",
            "color": "#ffeb3b",
            "custom": true,
            "count": 1
          }
        },
        {
          "space": true,
          "word": {
            "id": "4be6f72a-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "of",
            "slug": "of"
          },
          "entity": null
        },
        {
          "space": true,
          "word": {
            "id": "4be6f72b-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "Dream",
            "slug": "dream"
          },
          "entity": {
            "id": "7a074aa9-ce59-5926-8668-5bd6c77f1106",
            "name": "BAND",
            "slug": "band",
            "color": "#b9f6ca",
            "custom": true,
            "count": 1
          }
        },
        {
          "space": false,
          "word": {
            "id": "4be6f72c-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "Theater",
            "slug": "theater"
          },
          "entity": {
            "id": "7a074aa9-ce59-5926-8668-5bd6c77f1106",
            "name": "BAND",
            "slug": "band",
            "color": "#b9f6ca",
            "custom": true,
            "count": 1
          }
        }
      ]
    },
    {
      "source": "schedule a team meeting tomorrow 10:00 am",
      "language": {
        "isocode": "en"
      },
      "tokens": [
        {
          "space": true,
          "word": {
            "id": "4be6f72d-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "schedule",
            "slug": "schedule"
          },
          "entity": null
        },
        {
          "space": true,
          "word": {
            "id": "4be6f72e-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "a",
            "slug": "a"
          },
          "entity": null
        },
        {
          "space": true,
          "word": {
            "id": "4be6f72f-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "team",
            "slug": "team"
          },
          "entity": null
        },
        {
          "space": true,
          "word": {
            "id": "4be6f730-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "meeting",
            "slug": "meeting"
          },
          "entity": "undefined"
        },
        {
          "space": true,
          "word": {
            "id": "4be6f731-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "tomorrow",
            "slug": "tomorrow"
          },
          "entity": {
            "id": "391ada15-580c-5baa-b16f-eeb35d9b1122",
            "slug": "datetime",
            "custom": false
          }
        },
        {
          "space": true,
          "word": {
            "id": "4be6f732-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "10:00",
            "slug": "10-00-99"
          },
          "entity": {
            "id": "391ada15-580c-5baa-b16f-eeb35d9b1122",
            "slug": "datetime",
            "custom": false
          }
        },
        {
          "space": false,
          "word": {
            "id": "4be6f733-b60c-11e7-aa86-ddb3db21b6b8",
            "name": "am",
            "slug": "am"
          },
          "entity": {
            "id": "391ada15-580c-5baa-b16f-eeb35d9b1122",
            "slug": "datetime",
            "custom": false
          }
        }
      ]
    }
  ]
}
`

**Comment by lucasdchamps** [comment]
Hello,

I think the error message means that you should not specify the word parameter.

I could bulk create expression with the following post request:

```
curl -H "Authorization: Token MY_DEVELOPER_TOKEN" \
     -H 'Content-Type: application/json' \
     -d '{"expressions":[{"source":"wake me up tomorrow 6:30 am with Pull me Under of Dream Theater", "language":{"isocode":"en"}}, {"source":"schedule a team meeting tomorrow 10:00 am", "language":{"isocode":"en"}}]}' \
     -X POST "https://api.recast.ai/v2/users/MY_SLUG/bots/MY_BOT_SLUG/intents/MY_INTENT_SLUG/expressions/bulk_create"
```

You can find detail about this route here: https://man.recast.ai/#bulk-creating-expressions

I don't think you need all the values of word attributes.

Tell me if it works for you ;) Don't forget to replace MY_DEVELOPER_TOKEN, MY_SLUG, MY_BOT_SLUG and MY_INTENT_SLUG with your values.

P.S: Dream Theater FTW

**Comment by kazimanzurrashid** [comment]
Well if the bulk creation does not support up to token/word level then what is the purpose of it as I can create the expressions in bulk when creating the intent.

**Comment by kazimanzurrashid** [comment]
My use case is that I want to import it from a csv/db and I wanted to minimize the number of calls that I have to make in recast.

**Comment by lucasdchamps** [comment]
My bad, I didn't understand what you wanted to accomplish. I will try it out with all the fields.

You are absolutely right about the routes BTW. This route supports the token/word level while the intent creation does not.

**Comment by kazimanzurrashid** [comment]
Thank you.

**Comment by lucasdchamps** [comment]
I could reproduce and I analyzed your request in greater details.

Two things are surprising:

First, all the words in the request share the id `"4be6f721-b60c-11e7-aa86-ddb3db21b6b8"` and we don't have any word with this id in your DB. Plus, all words should have different ids in the request.

Second, a token is specified with the entity `"undefined"` which is incorrect, it should be `null`

**Comment by kazimanzurrashid** [comment]
Well your are right, i do not have any of the words, I started with only name attribute of word, then added the id and slug just to ensure that I am not missing any required attribute. so back to the original issue, the bulk creation api supports token/word ad if so what the required arguments over there?

**Comment by lucasdchamps** [comment]
The only required argument is an id. But it must be the id of an existing word. You are getting this error message because the specified word id does not refer to an existing word.

**Comment by kazimanzurrashid** [comment]
Well in that case we are back to the square one, you cannot create a word without an expression?

**Comment by lucasdchamps** [comment]
No you cannot but why do you need to specify words and entities when creating the expression? Do you wish to manually tag the expression with entities?

**Comment by kazimanzurrashid** [comment]
Well as I told you my original use case was to import/recreate the bot form a json/db with the minimal number of calls of the recast api and I was under the impression that bulk creation endpoint would come in handy in this case, but it seems it is the not what I expected.

**Comment by lucasdchamps** [comment]
So, you have a json/db of another bot that you wish to recreate in recast. Is it a bot from recast or are you migrating it from another platform?

The sentences in your db are already tagged right? That's why you want to specify the entities, correct?

**Comment by kazimanzurrashid** [comment]
Yes these jsons are collected from another system(not other bot platform) and it will be annotated/tagged as per your schema prior calling to recast.

**Comment by lucasdchamps** [comment]
Then you need to save valid word ids and entity ids in the jsons and it should work correctly

**Comment by kazimanzurrashid** [comment]
Well that means i need to know both the ids (entity & word )beforehand and as far as i know you do not have any endpoint which I can use to get the id for a given word. maybe it should be labeled as bulk updater instead of bulk creation.

**Comment by lucasdchamps** [comment]
You can get word and entity ids via the /expression route : https://man.recast.ai/#showing-an-expression

**Comment by kazimanzurrashid** [comment]
How can I call this endpoint when the whole conversation was itself was creating the expressions in bulk?

**Comment by lucasdchamps** [comment]
I'm not really sure I fully understand your use case, that's why I have trouble helping you. Can you describe in detail your pipeline, what information you have at each step and what you wish to perform?

**Comment by kazimanzurrashid** [comment]
Serialize the complete graph of an intent in json without any recast id, now try to create the intent from that json, example of an expression might be:

`{
  text: "wake me up tomorrow 6:30 am with Pull me Under of Dream Theater",
  annotations: [
  { word: "wake"},
  { word: "me"},
  { word: "up"},
  { word: "tomorrow", entity: "dateTime" },
  { word: "6:30 ", entity: "dateTime" },
  { word: "am ", entity: "dateTime" },
  { word: "with" },
  { word: "Pull", entity: "song" },
  { word: "me", entity: "song" },
  { word: "Under", entity: "song" },
  { word: "of" },
  { word: "Dream", entity: "band" },
  { word: "Theater", entity: "band:" }
  ]
}`

**Comment by lucasdchamps** [comment]
Ok, there is a way to do this:

In your post request to create the expression, never specify the word, only the entity. When there is no entity, just set `entity: null` and when there is an entity, provide a valid entity id.

You would have to fetch all entities first to have an index of valid entity ids.

**Comment by kazimanzurrashid** [comment]
I know I can use the create expression, but in that case I have to do it for each expression and that is the reason i wanted to use the bulk creation in order to reduce the number of calls, but i understand that your bulk creation does not support it and this why posted this issue here.

**Comment by lucasdchamps** [comment]
Yeah, I tried bulk creating expressions while specifying entities only and it is not valid.

You must specify the word id and entity id.

For your use case, the minimal number of calls you could do would be:
- bulk create all your expressions without entities
- for each expression
  * fetch the expression along with its words
  * update the expression to specify the entities
