### ISSUE TITLE
Built -> Action -> Changes not saved in GUI 

### ISSUE THREAD

**Issue by DrLDD** [RecastAI/Recast.AI#20]
When changing the values (requirements) they are not saved.

Befor:
![image](https://user-images.githubusercontent.com/7447054/31878735-587243b6-b7db-11e7-8b91-9809267aefb7.png)

My change:
![image](https://user-images.githubusercontent.com/7447054/31878768-7352d650-b7db-11e7-8c17-10520aa74d18.png)

But change will not be saved.

**Comment by andrewfonseca** [comment]
I'm getting this behavior as well. Sometimes hitting F5 helps, but it is kinda random.
