### ISSUE TITLE
Expose an endpoint that returns only Gold Entities

### ISSUE THREAD

**Issue by kazimanzurrashid** [RecastAI/Recast.AI#21]
Currently the /entities endpoint returns a gigantic list entities created by all recast user, can you pls add an endpoint that returns the gold entities.

Also can we have  some kind of filter in /entities endpoint, i mean it will return the entities that matches keyword e.g. /entities?q=SOME_PREFIX

**Comment by lucasdchamps** [comment]
Hello,

thanks for the feedback and idea. I would say it is not our priority to add this kind of functionality to the /entities route. For now, you would need to filter the returned list yourself.

Don't hesitate to ask if you need help about the filtering ;)

**Comment by kazimanzurrashid** [comment]
What about an endpoint that returns your gold entities?

**Comment by lucasdchamps** [comment]
Same answer :| it would be a useful route but it's not a top priority. We'll keep it in mind though, thanks again for the feedback ;)
