### ISSUE TITLE
Internal Server Error when using message.reply()

### ISSUE THREAD

**Issue by developpef** [RecastAI/Recast.AI#22]
Hi,
I am facing a technical error when trying to answer a message coming from a connector (Slack) (all is working fine when responding to raw requests coming directly from API).

The error is raised when calling (in NodeJS) :

`message.addReply([{ type: 'text', content: reply }])
 return message.reply()
		  .then(res3 => console.log('message sent'))
		  .catch(err => console.error('Something went wrong2', err))`

Here is the stack trace. Can you help?

`Nov 29, 2017 04:54 PM +01:00
Something went wrong { Error: Internal Server Error
    at Request.callback (/var/task/node_modules/superagent/lib/node/index.js:626:17)
    at /var/task/node_modules/superagent/lib/node/index.js:795:18
    at IncomingMessage.<anonymous> (/var/task/node_modules/superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  original: null,
  response: 
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 500,
        statusMessage: 'Internal Server Error',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        text: '{"errors":{"channel":{"message":"Path `channel` is required.","name":"ValidatorError","properties":{"type":"required","message":"Path `{PATH}` is required.","path":"channel","value":null},"kind":"required","path":"channel","value":null,"$isValidatorError":true}},"_message":"Conversation validation failed","message":"Conversation validation failed: channel: Path `channel` is required.","name":"ValidationError"}',
        read: [Function],
        body: [Object] },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        _agent: false,
        _formData: null,
        method: 'POST',
        url: 'https://api.recast.ai/connect/v1/conversations/169a9db7-79c6-48d1-8bcb-2c8c47a6a3ed/messages',
        _header: [Object],
        header: [Object],
        writable: true,
        _redirects: 0,
        _maxRedirects: 5,
        cookies: '',
        qs: {},
        qsRaw: [],
        _redirectList: [],
        _streamRequest: false,
        _data: [Object],
        req: [Object],
        protocol: 'https:',
        host: 'api.recast.ai',
        _callback: [Function],
        res: [Object],
        _timeout: 0,
        response: [Circular],
        called: true },
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: 51,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /connect/v1/conversations/169a9db7-79c6-48d1-8bcb-2c8c47a6a3ed/messages HTTP/1.1\r\nHost: api.recast.ai\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: node-superagent/2.3.0\r\nAuthorization: Token ed665077a9496e5fafc6a49f065bf225\r\nContent-Type: application/json\r\nContent-Length: 51\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/connect/v1/conversations/169a9db7-79c6-48d1-8bcb-2c8c47a6a3ed/messages',
        _ended: true,
        parser: null,
        res: [Object] },
     links: {},
     text: '{"errors":{"channel":{"message":"Path `channel` is required.","name":"ValidatorError","properties":{"type":"required","message":"Path `{PATH}` is required.","path":"channel","value":null},"kind":"required","path":"channel","value":null,"$isValidatorError":true}},"_message":"Conversation validation failed","message":"Conversation validation failed: channel: Path `channel` is required.","name":"ValidationError"}',
     body: 
      { errors: [Object],
        _message: 'Conversation validation failed',
        message: 'Conversation validation failed: channel: Path `channel` is required.',
        name: 'ValidationError' },
     files: undefined,
     buffered: true,
     headers: 
      { date: 'Wed, 29 Nov 2017 15:54:48 GMT',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '413',
        connection: 'close',
        server: 'nginx',
        'x-powered-by': 'Express',
        'access-control-allow-origin': '*',
        'access-control-allow-headers': '*, X-Expiry, X-Client, X-Access-Token, X-Uuid, Content-Type, Authorization',
        'access-control-expose-headers': 'X-Client, X-Access-Token, X-Expiry, X-Uuid',
        'access-control-allow-methods': 'GET, DELETE, POST, PUT, OPTIONS',
        'access-control-max-age': '86400',
        'cache-control': 'private, no-cache, no-store, must-revalidate',
        expires: '-1',
        pragma: 'no-cache',
        etag: 'W/"19d-WspfrkeEtjJZiYw9KuCVciMrAyE"',
        'x-kong-upstream-latency': '71',
        'x-kong-proxy-latency': '0',
        via: 'kong/0.10.3' },
     header: 
      { date: 'Wed, 29 Nov 2017 15:54:48 GMT',
        'content-type': 'application/json; charset=utf-8',
        'content-length': '413',
        connection: 'close',
        server: 'nginx',
        'x-powered-by': 'Express',
        'access-control-allow-origin': '*',
        'access-control-allow-headers': '*, X-Expiry, X-Client, X-Access-Token, X-Uuid, Content-Type, Authorization',
        'access-control-expose-headers': 'X-Client, X-Access-Token, X-Expiry, X-Uuid',
        'access-control-allow-methods': 'GET, DELETE, POST, PUT, OPTIONS',
        'access-control-max-age': '86400',
        'cache-control': 'private, no-cache, no-store, must-revalidate',
        expires: '-1',
        pragma: 'no-cache',
        etag: 'W/"19d-WspfrkeEtjJZiYw9KuCVciMrAyE"',
        'x-kong-upstream-latency': '71',
        'x-kong-proxy-latency': '0',
        via: 'kong/0.10.3' },
     statusCode: 500,
     status: 500,
     statusType: 5,
     info: false,
     ok: false,
     redirect: false,
     clientError: false,
     serverError: true,
     error: 
      { Error: cannot POST /connect/v1/conversations/169a9db7-79c6-48d1-8bcb-2c8c47a6a3ed/messages (500)
          at Response.toError (/var/task/node_modules/superagent/lib/node/response.js:106:13)
          at Response._setStatusProperties (/var/task/node_modules/superagent/lib/node/response.js:183:12)
          at new Response (/var/task/node_modules/superagent/lib/node/response.js:42:8)
          at Request._emitResponse (/var/task/node_modules/superagent/lib/node/index.js:659:20)
          at /var/task/node_modules/superagent/lib/node/index.js:795:38
          at IncomingMessage.<anonymous> (/var/task/node_modules/superagent/lib/node/parsers/json.js:16:7)
          at emitNone (events.js:91:20)
          at IncomingMessage.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:974:12)
          at _combinedTickCallback (internal/process/next_tick.js:80:11)
        status: 500,
        text: '{"errors":{"channel":{"message":"Path `channel` is required.","name":"ValidatorError","properties":{"type":"required","message":"Path `{PATH}` is required.","path":"channel","value":null},"kind":"required","path":"channel","value":null,"$isValidatorError":true}},"_message":"Conversation validation failed","message":"Conversation validation failed: channel: Path `channel` is required.","name":"ValidationError"}',
        method: 'POST',
        path: '/connect/v1/conversations/169a9db7-79c6-48d1-8bcb-2c8c47a6a3ed/messages' },
     accepted: false,
     noContent: false,
     badRequest: false,
     unauthorized: false,
     notAcceptable: false,
     forbidden: false,
     notFound: false,
     charset: 'utf-8',
     type: 'application/json',
     setEncoding: [Function: bound ],
     redirects: [] },
  status: 500 }
`

**Comment by janteuni** [comment]
Hello @developpef 
Sorry for the delay, is the issue still there ?

**Comment by developpef** [comment]
No, I improved error management and used axios library to improve promises behaviour, and problem is solved.
