### ISSUE TITLE
Endless replies on messenger

### ISSUE THREAD

**Issue by rohit-mathur** [RecastAI/Recast.AI#24]
I made a chatbot with greeting, small talk and weather as pre-defined skills. Then i just connected it to the messenger, following the steps written in documentation. Now basically, I am facing two problems:

1. The bot is endlessly replying to how are you, as it was the last text sent by me as a user or i can say the bot is receiving text endlessly, as i checked under the monitor tab, it has over 900 entries of how are you and still counting.
2. The bot isn't replying to anyone else. I tried to chat with the bot, it replies endlessly to the account which was used to create the facebook app. It does not reply at all to any other user.

**Comment by dbousque** [comment]
Hi @rohit-mathur, is it still responding ? Could you send me (by mail if you want, at dominik@recast.ai) your username, as well as the name of your bot ?

**Comment by dbousque** [comment]
The problem was that the Messenger application was registered to `message_echoes` events on the Facebook page.

**Comment by Piyushhbhutoria** [comment]
Still struggling with this issue. please help!
