### ISSUE TITLE
twitter chatbot

### ISSUE THREAD

**Issue by hadeelphp** [RecastAI/Recast.AI#25]
i trying to connect my bot with twitter, I make all steps to make the connection,, I create twitter app and copy the credentials (Consumer Key, etc ) ,,, but I have this error: Something went wrong, please check your credentials

**Comment by hadeelphp** [comment]
please can anyone help me 
look at the screenshot 
http://prntscr.com/i9vbw6

**Comment by prasinuslux** [comment]
Did you follow the instructions in the connector tab? There must've been something you did wrong.

**Comment by DimoHG** [comment]
I have the same issue. I have successfully created a developer account and followed the tutorial strictly. The Facebook connection is working for my bot, but the Twitter one has this exact error message every time.

**Comment by janteuni** [comment]
Hello, do you still have this error with Twitter?

**Comment by aurelie-lamy** [comment]
Hello @DimoHG, hello @hadeelphp,

Do you still have the error?

Thanks!
