### ISSUE TITLE
Webhook call to Java Rest service

### ISSUE THREAD

**Issue by Sandra-A** [RecastAI/Recast.AI#28]
Sorry if this is not the right place to post my question.
If I have a REST service in java or .NET can I use webhooks to send a request and response back to my bot? Thank you

**Comment by Sandra-A** [comment]
I'm sending this in my service response:
![recastresponse](https://user-images.githubusercontent.com/20441222/36496743-e2384bcc-16fe-11e8-96c5-f2adb1a4a12c.png)

But recast shows "No replay"

**Comment by Sandra-A** [comment]
I fix this. The problem was I send the json the wrong way (as string) I just change thaht and now works.

**Comment by x00119297** [comment]
Hi Sandra, can you explain your solution in a little more detail please? What way do you send the JSON now?
