### ISSUE TITLE
not able to import csv file

### ISSUE THREAD

**Issue by guiloport** [RecastAI/Recast.AI#29]
I cannot upload a *.csv file to upload a list of expressions to create a gazette for a custom entity, even though the the file should be accepted.

I get error "Csv parameter format is not supported (accepted format is 'text/csv')"

The file is this, but in txt format.

[SFMODULES.csv.txt](https://github.com/RecastAI/Recast.AI/files/1763538/SFMODULES.csv.txt)

My bot is this: https://recast.ai/guiloport/analyse-text-talking-bot/train

Any help would be appreciated.

Thanks and best regards,

Guillermo

**Comment by AnRRm** [comment]
Hey,
I am facing a similar issue here.
Any solution ?

**Comment by raghuvirab** [comment]
i am facing the same issue. Tried all combinations but to no avail. Any suggestions?

**Comment by lucasdchamps** [comment]
Hello all,

There is an ongoing issue regarding import of csv files created on Windows: https://github.com/RecastAI/Recast.AI/issues/36

The format is not supported.

It sould be fixed this summer
