### ISSUE TITLE
Training mechanics with default entities?

### ISSUE THREAD

**Issue by jb-kerboeuf** [RecastAI/Recast.AI#31]
Hello,

I have a hard time understanding how the bot learns and how I should train it. Sometimes it seems like it just doesn't take my training inputs into account.

I have a flight-booking bot, and when I say only 'Sydney' (as an answer to "where will you go?" for example) it's tagged as a "PERSON ★" entity, but I tagged it as a "LOCATION ★", in multiple sentences, in multiple intents, in multiple position and casing... and it just doesn't care. The confidence doesn't even lower. Same problem with "the Bund" (an area of Shanghai), I tagged it as a "LOCATION ★" but it doesn't learn.

So considering the lack of information on this topic, I made a very basic test bot to investigate
 - I have two intents 'japanese' and 'italian'; 
 - in french, 'italien' is a training expression without entities, in the 'italian' intent;
 - when I say 'italien' in french, the bot wrongly tags it as a 'language' and the intent is 'japanese' with 0.5 confidence;

Does that mean that when the bot finds an entity it doesn't look at the word? it's just left with a wrongly tagged entity and doesn't know what to do with it?

Can I train "Sydney" to be a "LOCATION ★"?
Can I train "italien" to NOT be a "LANGUAGE ★"?
Can I totally disable the default ★ entities ? 
Can I give values to my custom entities ? like "two" has a value "2"

Thank you very much :)

**Comment by indispira** [comment]
Hi, we are working on a new feature to solve this problem, coming soon.

**Comment by jb-kerboeuf** [comment]
Any update ? Could you share some details about what's "coming soon" ? :)

**Comment by thbeucher** [comment]
Hello, 
Currently this mechanism is available:
In your skills, when you fill requirements with expected entity and provide a question in order to retrieve it, the user answer to this question will be analyzed knowing that a particular entity is expected.
