### ISSUE TITLE
not able to fork projects from the community

### ISSUE THREAD

**Issue by simatao** [RecastAI/Recast.AI#32]
hi,
whenever i want to fork an existing bot, i get locked out of the system and get a message "fork failed".
https://recast.ai/recast-ai/weather-bot/train

**Comment by lucasdchamps** [comment]
Hello @simatao 

I think this behavior has been fixed. Can you try again please?

**Comment by simatao** [comment]
Thanks, it's working now. Just successfully synced two different weatherbots. (none of them displays the forecast though ;-)
