### ISSUE TITLE
Automatically create an action

### ISSUE THREAD

**Issue by Alexandre-Lara** [RecastAI/Recast.AI#33]
Hello, 

I'm an SAP Employee and I have a doubt,

How can create an action via API, the same way as I do when I deal with creating an Intent via POST HTTP Request?

Thanks in advance, 

Alexandre Lara
Pre-Sales Specialist | alexandre.lara@sap.com

**Comment by OlivierNguyen** [comment]
Hello,

Unfortunately, the API endpoint which allows you to create actions is not documented and probably won't because it is not open yet.

Best regards.
Olivier

**Comment by OlivierNguyen** [comment]
To do it, you can inspect each call used when creating an action in the Developer console of your browser. But there are not public documentation for that.
