### ISSUE TITLE
Unable to integrate the chat window

### ISSUE THREAD

**Issue by gkakkar** [RecastAI/Recast.AI#34]
We are integrating the chat window in our website. it is working fine in first page but as soon as we navigate to othe page following is observed:

1.Script is intercepting with the url of page and causing the reload of first page(means navigation of our web page is not working)

Information:
1.we have made our website using Angular 2.
2 we are using the below script for our website:
<script src="https://cdn.recast.ai/webchat/webchat.js"
channelId="ourchannalid"
                               token="ourbottoken"
id="recast-webchat"
></script>

**Comment by OlivierNguyen** [comment]
If the bug is still here, is it possible to have a small project that can reproduce this issue ? It will be easier to find and fix with it. But without context, it is complicated to tell if it is a bug from Angular or our script (which use React).
