### ISSUE TITLE
How do i connect my bot to heroku?

### ISSUE THREAD

**Issue by DrAwesomexX** [RecastAI/Recast.AI#42]

**Comment by LarsVlyminckx** [comment]
I can help you with that. Which language did you use? If Python you can use this (https://recast.ai/blog/github-repo-heroku). If you use NodeJS I can help you.

**Comment by DrAwesomexX** [comment]
I used Node.js

**Comment by LarsVlyminckx** [comment]
First you need to create a file called "Procfile" with this code `web: node index.js` (index.js is your main file). Afterwards you need to create a repository. Then you create an account on Heroku. After you logged in you make an new app. Create URL, link to your github repository and it will automatically install everything. Afterwards you link your URL to your bot setting in Recast.

**Comment by DrAwesomexX** [comment]
Thank you so much, Sir

**Comment by LarsVlyminckx** [comment]
No problem.
(I think you can close this issue)
