### ISSUE TITLE
Request cannot be processed without authentication error

### ISSUE THREAD

**Issue by prasinuslux** [RecastAI/Recast.AI#45]
So I have this code: 

`from recastai import Connect`
`import recastai`
`from flask import Flask, request, jsonify`

`client = recastai.Client('894c7ddc059a3e4c3e71777c933a31de')`
 

`def bot(request):`
  `message = client.connect.parse_message(request)`
  `content = message.content`
  `type = message.type`
   `conversation_token = message.sender_id`
  
 ` if type == 'text':` 
     `response = request.converse_text(content, conversation_token)`
    `reply = response.reply` 
     `connect.send_message([{ 'type': 'text' , 'content': reply }], message.conversation_id)`

  `return jsonify(status=200)`

`app = Flask(__name__)`
`@app.route('/', methods=['POST'])`
`def root():`
  `return bot(request)`

`app.run()`

And I keep getting the error 
"Request cannot be processed without authentication" as soon as I send a message to the bot from my connected channel. Why is this? I'm supposing the problem is here

` 
response = request.converse_text(content, conversation_token)
` 

or here

`
message = client.connect.parse_message(request)
`

And I've even tried adding 
`request = recastai.Request('894c7ddc059a3e4c3e71777c933a31de', 'en')
`
inside my if statement to see if I can authenticate that way but that was only an educated guess which comes under the assumption that `request.converse_text` is even a valid method . The documentation isn't informative enough IMO. Not to mention the code examples on Github don't even work. Utter disappointment.

**Comment by dbousque** [comment]
Hi @prasinuslux :) Sorry, the Wiki is not up to date on the Python SDK. This part of the code :
```
if type == 'text':
  response = request.converse_text(content, conversation_token)
  reply = response.reply
```
Should be this instead (not tested) :
```
if type == 'text':
  response = client.dialog(content, conversation_token)
  reply = response.messages[0] if len(response.messages) > 0 else 'The bot remained speechless'
```
But overall, if you need your bot to talk in one of our supported channels, it's quite a bit easier to just go trough the platform only, no code required. Go to the 'Connect' tab of your bot, you'll find instructions on how to connect your bot to your channel. If you really need to explicitly call your bot from your code, you can also take a look at the API : https://recast.ai/docs/api-reference/#dialog-text

**Comment by prasinuslux** [comment]
The debugger told me the 'Client' object has no dialog attribute. In other words, 

  `response = client.dialog(content, conversation_token)` 

did not work properly. What's the deal here? Also, I've connected my bot on Messenger, but I want my bot to respond FROM messenger. Wouldn't that require programming on my part?

**Comment by dbousque** [comment]
Which version of the `recastai` package are you using ?
No, you don't need any programming for your bot to respond to people on Messenger :) Make sure your bots works using the webchat on the platform, then configure a Messenger channel in the 'Connect' tab, and your bot should now respond to you on Messenger.
