### ISSUE TITLE
[BUG] Language detected is always the same as processing language other than when set to AUTO

### ISSUE THREAD

**Issue by Ambritalian** [RecastAI/Recast.AI#49]
So I am trying to give a response in the same language that the user is speaking, but if my bot's default language is English and I speak to it in French, the bot recognises "comment allez vous" as English instead of French. The situation is the same in a vice-versa situation.

This being said, the behaviour appears to be correct in the "TEST" section, when language: AUTO is selected. i.e. the bot recognises the language appropriately.

As a summary, I do not believe that the bot is behaving as specified by the language section of the documentation. Please see the first point under "example", link provided for ease of access. https://recast.ai/docs/language.

**Comment by dbousque** [comment]
Hi @Ambritalian , the language is fixed for a conversation, it doesn't change automatically. So if you start a new conversation, the language will be the right one. If you want to change the language midways, you can use the bot-builder action dedicated to that. Those comments, as well as your observations only apply to the bot-builder, not the NLP API, which https://recast.ai/docs/language describes.

**Comment by Ambritalian** [comment]
Hi @dbousque I tried to use the bot-builder action to change the language half way through a conversation, but it does not - the language stays the same.

I am trying  to catch which language (En/Fr) the user is speaking and then changing the conversation language to match it (and giving a fixed reply in that language) but the reply always stays the same.
