### ISSUE TITLE
Cannot change language more than once per conversation with bot builder

### ISSUE THREAD

**Issue by Ambritalian** [RecastAI/Recast.AI#50]
From my previous post yesterday, @dbousque said to use the conversation language bot action in order to change the language during a conversation. This I have tried, but have found that it does not allow you to change the language again during the same conversation. 

I'm trying to build a bot that replies in the same language as the user speaks, pulling the responses from an external API by seeing which language the request was sent in. For some reason, even when i type in french I always receive the language as english.

**Comment by Ambritalian** [comment]
Please see the extract from a script i wrote to find the languages analysed:
where is the soho room?
conv lang:en
nlp lang:en
nlp proc lang:en

ou est la salle soho?
conv lang:en
nlp lang:en
nlp proc lang:en

**Comment by dbousque** [comment]
Switching languages works fine :) I made an example for you here : https://recast.ai/dominik/multi. You can fork the bot to talk to it. This is a sample conversation : 

![switch_language](https://user-images.githubusercontent.com/16238354/41974316-eb5359a0-7a17-11e8-9bd2-189296ba12e4.png)
