### ISSUE TITLE
Whether we can get multiple responses when calling /dialog endpoint

### ISSUE THREAD

**Issue by TechSkieur** [RecastAI/Recast.AI#51]
Hi,

There is one text, after intent detection, two intents might be matched for this text. Let's say Intent A and Intent B.

In our Skill setting, Intent A will trigger Skill A, which will send Response A; while Intent B will trigger Skill B, which will send Response B.

In such case, when we calling /dialog endpoint, can we get both Response A and Response B? It looks like only one response matched to highest confidence level will be returned. But from the API doc, the message field is an array, it should be able to contain multiple messages inside it.

Or is there a way we can get both Response A and Response B?

Thanks.

BRs,

yangyang

**Comment by dbousque** [comment]
Skills don't have to be triggered by an intent. They can be triggered by anything, an entity, the time of the day, the state of the memory, the language the conversation takes place in, and other stuff, as well as any combination (AND/OR nested twice) of those elements.
So the intents detected have no influence whatsoever to the responses you generate, you are free to do anything you like. You can generate an arbitrary number of responses, there is no limit.
