### ISSUE TITLE
[Question]How many Bots would customers normally use in real scenario

### ISSUE THREAD

**Issue by TechSkieur** [RecastAI/Recast.AI#53]
Hi expert,

We are integrating our product with Recast.AI. We are curious about how many Bots would customers normally use in real scenario. Would they normally deploy only one Bot to different channels? Or in other words, in what cases would a customer would use more than one Bot?

Based on this input, we can have a deeper understanding on Bot Integration. Thanks a lot:)

BRs,

yangyang

**Comment by dbousque** [comment]
People typically use one bot if they want handle a small use-case, multiple bots otherwise. But you can do anything you like, there are no technical constraints. I have a bot with 150 skills for example.

**Comment by TechSkieur** [comment]
Thanks @dbousque 

Would this kind of case appear often in reality? For instance I deploy a Bot to Facebook channel, while another Bot to Line channel ? Use different Bots for different Channels. Or use different Bots for different message types (text, voice, websocket)

yangyang
