### ISSUE TITLE
numbers not recognized in Russian bot version

### ISSUE THREAD

**Issue by NatKut** [RecastAI/Recast.AI#54]
Hello, in our multilingual bot we have a problem in Russian version. The numbers are not recognized there as a gold entity. But it works well for English and German versions. How can we solve this problem?
![grafik](https://user-images.githubusercontent.com/40826028/42273092-7bb2053a-7f88-11e8-9b5e-f4f77b789f46.png)

**Comment by dbousque** [comment]
Hi @NatKut. Gold entities are available in 4 languages right now : english, german, spanish and french. Take a look here : https://recast.ai/docs/language
