### ISSUE TITLE
Gazzete Entity has already been taken Error

### ISSUE THREAD

**Issue by andreifpopescu** [RecastAI/Recast.AI#56]
I created a new gazette to test something. Then I disabled that and created a new gazette. Now when I try to make the new gazette a closed gazette or when I try to disable it, an error shows up : "Entity has already been taken", and no change is made.

**Comment by aurelie-lamy** [comment]
Hi @andreifpopescu , do you still have this issue?
If yes, can you provide me the link of your bot and the name of your gazette?

Thanks,

**Comment by andreifpopescu** [comment]
Hi,

Yes, the problem still persists.
Bot link: https://recast.ai/ra-1/booking-bot
Gazzete name: HELP_TYPE
But the problem occured on all gazzets
I was a collaborator and the bot is set to private.
The bot was used in a demo presentation and it’s not in use anymore.

Best regards,

Andrei

**Comment by aurelie-lamy** [comment]
Hi,

We did an action on your bot, if you test again, you will not have the issue :)

Thanks for your answer!
