### ISSUE TITLE
Trouble Whit Cards

### ISSUE THREAD

**Issue by AladMocu** [RecastAI/Recast.AI#57]
Im trying to build a restaurant bot, it was working some weeks ago but now im getting a little problem when im sending cards
when im trying it on recast it works 

![recast](https://user-images.githubusercontent.com/25905130/42529776-fc9d2042-8444-11e8-9568-36e5e60818ef.JPG)

but when I use it on messenger it just do this:

![messenger](https://user-images.githubusercontent.com/25905130/42529744-e99819f2-8444-11e8-9a69-00fdc534b210.JPG)

**Comment by janteuni** [comment]
Hello @AladMocu do you still have this issue on your bot?

**Comment by AladMocu** [comment]
Im back after a few months, still having the issue
