### ISSUE TITLE
Can a text message in "Action" contain url as hyperlink

### ISSUE THREAD

**Issue by archanarai2211** [RecastAI/Recast.AI#61]
I am using text message to reply to certain intends. The message contains text as well as links. 
For e.g. 
If you want more information follow this link: https://moreinfo/getDetails

I actually don't want to show the whole link to the user ,instead some customized text for the link
e.g.
If you want more information follow [this link](https://moreinfo/getDetails)

Also, I don't want button for it. Just a hyperlink in the text.

Thanks,
Archana

**Comment by ftriquet** [comment]
Hello, actually this depend on the channel you use. For example, Messenger supports markdown formatting, meaning that you can achieve what you want by writing: "If you want more information follow [this link](https://moreinfo/getDetails)". But we dont do it as part of the builder.
