### ISSUE TITLE
[Question/Help] Chatbot unable to answer, send alert to creator/owner

### ISSUE THREAD

**Issue by LarsVlyminckx** [RecastAI/Recast.AI#62]
Hello

I just found these videos on your website (https://recast.ai/companies "Check the top 4 bots").
I just saw this video (https://youtu.be/pz2QYNMB5_w "Service bot - HR chatbot") and I want to create it myself.

In the video they give an alert to the creator/owner if the bot doesn't know the answer. So he can give an correct answer instead of the bot gives an reply like "Sorry I don't know that". 

Is there any tutorial or documents how to create this? 

Thanks in  advance

**Comment by dbousque** [comment]
Hi @LarsVlyminckx. You can setup a "fallback channel" in the 'Connect' tab of your bot.
