### ISSUE TITLE
[Question]Userlogin to memory

### ISSUE THREAD

**Issue by LarsVlyminckx** [RecastAI/Recast.AI#63]
Hi

I have an idea. My vision: I want to make a chatbot to request vacation for a company. The employee logs in on the website of the company website and start talking to the chatbot. But instead of the bot asks his name, the bot knows his name because he is logged in. Does somebody know how to code/implement this. Because I don't know how to do it and there isn't an API call to give the name to the memory. 

Thanks in advance

**Comment by dbousque** [comment]
If you have your own webchat, you can put data in the memory of the conversation when it starts : https://recast.ai/docs/api-reference/#dialog-endpoints. Otherwise, you could edit our open source webchat (https://github.com/RecastAI/Webchat) to do anything you like. For example, you can update the memory of the conversation with this endpoint : https://recast.ai/docs/api-reference/#update-a-conversation.

**Comment by LarsVlyminckx** [comment]
Thank you!
I will try it, I'll keep you informed

**Comment by LarsVlyminckx** [comment]
Hi

I'm trying this:
`build.dialog({ type: 'text', content: 'test'}, { conversationId: '1' }, {memory: { 'person': 'your_value'}})`
but i can't send memory to the bot. Can you give me an example?

**Comment by dbousque** [comment]
I think the ability to send a memory to `dialog` was not added to the SDK yet, but you can use the API directly instead. Personally I prefer to use it over SDKs.

**Comment by LarsVlyminckx** [comment]
What do you mean?
I copied to code from your first link: (https://recast.ai/docs/api-reference/?javascript#dialog-text) and it send to message but not the memory.
You mean I need to make a post request instead of the SDK (the javascript code from the link?)?

**Comment by LarsVlyminckx** [comment]
It is working in the console.

```
person.fullname = 'John Doe'
memory: { person: person.fullname, role:person.role }
```

```
responses [ { type: 'text', content: 'It is working' },
{ type: 'text', content: 'Hello John Doe' } ]
```
But when I say "Hi" in my chatbot it gives me "Hello undefined"
and my memory is empty.

**Comment by dbousque** [comment]
Can you send me the code you're using to call `/dialog` ?

**Comment by LarsVlyminckx** [comment]
You mean this:
```
console.log(req.body.conversation.memory)
    const person = req.body.conversation.memory.person;
    res.send({
        replies: [
            {
                type: 'text',
                content: `Hello ${person}`,
            },
        ]
    })
```
result > {} (console.log)

**Comment by dbousque** [comment]
No :) The code calling `/dialog`

**Comment by LarsVlyminckx** [comment]
You mean this?
```
 const headers = { Authorization: `Token ${config.DEVELOPER_TOKEN}`, 'Content-Type': 'application/json' }
        const message = { type: 'text', content: 'test!' }
        const body = { conversation_id: '12345', message, memory: { person: person.fullname, role:person.role } }
        axios.post('https://api.recast.ai/build/v1/dialog', body, { headers })
            .then(res => {
                console.log(res.data)
                console.log('responses', res.data.results.messages)
            })
            .catch(err => console.error(err.response.data))
```
I copied your example and just added my memory

**Comment by dbousque** [comment]
If all you got is this, then yes, `memory.person` will be undefined, since I don't see `person` declared.

**Comment by LarsVlyminckx** [comment]
No because this is strange.

```
const headers = { Authorization: `Token ${config.DEVELOPER_TOKEN}`, 'Content-Type': 'application/json' }
            const message = { type: 'text', content: 'test!' }
            const body = { conversation_id: '12345', message, memory: { person: person.fullname, role:person.role } }
            axios.post('https://api.recast.ai/build/v1/dialog', body, { headers })
                .then(res => {
                    console.log('responses', res.data.results.messages)
                })
                .catch(err => console.error(err.response.data))
```
Console returns: 
```
{ person: 'Lars Vlyminckx', role: 'admin' }
responses [ { type: 'text', content: 'It is working' },
  { type: 'text', content: 'Hello Lars Vlyminckx' } ]
```
-----------------------------------------------------------------------
Say "test" to chatbot (for testing :p )

```
console.log(req.body.conversation.memory)
    const person = req.body.conversation.memory.person;
    res.send({
        replies: [
            {
                type: 'text',
                content: `Test ${person}`,
            },
        ]
    })
```
Console return
`{}`
and chatbot says "Test undefined"

**Comment by dbousque** [comment]
I don't understand what you are talking about. What do you mean by "console" ? If you call `/dialog` directly, you can't use our webchat (be it on the platform or as a channel), since you send and receive messages from and to `/dialog`, so it's your job to bring messages to it, and do something with the responses (probably send them to a channel, but you must do that manually, through this endpoint for example : https://recast.ai/docs/api-reference/#send-a-message)

**Comment by LarsVlyminckx** [comment]
I'm sorry. What I meant: I wanted to login and pass it (via the `/dialog` api call) to the chatbot and then you can start chatting with the chatbot from the Webchat.
You mean if I send it with `/dialog` I need to continue with api Calls and not via the Webchat.
So actually the api call and webchat on the same page are 2 different "connection" to the bot?

**Comment by dbousque** [comment]
You can't use our webchat as is to do what you want. You need to either modify it to suit your needs (https://github.com/RecastAI/Webchat) or have your own webchat. The reason is that you can't set a memory to a conversation that doesn't exist yet. So you need to call `/dialog` manually and pass a memory as argument to start the conversation, and for all following messages, you also need to call `/dialog` manually.

**Comment by LarsVlyminckx** [comment]
Okay I get it.
Is it possible to add a memory to the webchat from Github? (https://github.com/RecastAI/Webchat). If so can you give me example, or do I need to add it to Github myself and modify the code? Because I have no idea how to do it. Or is it possible Recast can add it themself to the (Github) Webchat?

**Comment by dbousque** [comment]
You can do it and make a PR, we would gladly accept it :) We may implement this one day, it's in our plans, but it's not coming soon.

**Comment by LarsVlyminckx** [comment]
I would like to help you but I have no idea how to do/make it. Can you give me an example or something

**Comment by dbousque** [comment]
You can start by building the webchat and running it locally. When that's done, you can start tinkering with it

**Comment by LarsVlyminckx** [comment]
Okay I will try. I'll keep you informed.

**Comment by LarsVlyminckx** [comment]
Hi

I tried to create it but I didn't succeed. Is there any change you will add this in the future?

**Comment by dbousque** [comment]
Hi @LarsVlyminckx. Yes, it is currently being prepared, it should be released in the next few months.

**Comment by dbousque** [comment]
Hi @vighnesh27, it will be released at the end of November. You can take a look at the MR for the documentation here : https://github.com/RecastAI/docs/pull/57/files, it will allow you to prepare for when it's released :)
