### ISSUE TITLE
[Question]When fallback channel is triggered, will the new message always go to human agent

### ISSUE THREAD

**Issue by TechSkieur** [RecastAI/Recast.AI#64]
Hi expert,

I have one question is that in such scenario: customer says something with unclear intent => go to fallback channel => Human agent takes over  => Customer again sends over a message with clear intent => will this message be able to pass over to the agent or will again be handled by bot directly? Is there any guide/configuration to explain this kind of case?

Thanks.

yangyang

**Comment by dbousque** [comment]
Hi there, the human agent must close the conversation for the bot to take over again.

**Comment by TechSkieur** [comment]
@dbousque Sorry, I don't quite understand...Do you mean in such case, human agent needs to close the conversation between Fallback channel and Bot? Then if this customer says something undetected for a second time, then human agent will be involved again?

We thought after human agent is involved for the first time, he/she can stay in the conversation, and talk with customer continuously on behalf of Bot until the whole conversation ends. Looks like our assumption is wrong?

yangyang

**Comment by dbousque** [comment]
Fallback channels are simple :
  - the user talks to the bot through a channel (non-fallback)
  - at some point, you decide that the agent should take over the conversation
  - so you execute a 'fallback' action in the builder
  - from now on, messages send by the user are received by a human agent
  - the conversation with the human agent continues as long as this agent doesn't close the conversation from his dashboard.
  - when it happens, the bot takes over the conversation again
You can fallback the conversation as many times as you want.

**Comment by TechSkieur** [comment]
Thanks @dbousque  Perfect answer:)
