### ISSUE TITLE
Webhooks POSTing Empty Data

### ISSUE THREAD

**Issue by mattlemmone** [RecastAI/Recast.AI#68]
Hello,

Ever since the newer webhooks were introduced, my bot stopped working. Webhooks used to post the expected data (conversation id, etc) correctly to my endpoint. Now I am only receiving an empty JSON object. My goal is to use the "default" body template since I only need access to the conversation id.

I have been able to POST and use data on my server using a client other than Recast, so I know there is no issue with my server.

**Comment by aymen-mouelhi** [comment]
@ftriquet I have the same issue. I am using flask, from a local web server it seems that it is working correctly. Once it is deployed to heroku, I receive the webhook but without any POST data. I tried setting the Content-Type to application/json, but that didn't fix the issue.

**Comment by ftriquet** [comment]
@aymen-mouelhi  Do you use http auth in your webhook?

**Comment by dbousque** [comment]
@aymen-mouelhi This is a know flask issue, update to the latest version :)
