### ISSUE TITLE
[Help] Entitie for vehicle's plate.

### ISSUE THREAD

**Issue by yimialejoh** [RecastAI/Recast.AI#69]
Hello, I need to create an entity that captures the license plates of the vehicle (NUMPLACA), example KFV740, WAO050, but it is not very precise detecting it, Any idea of how I can do it?

![prueba](https://user-images.githubusercontent.com/38698937/44590915-de7aa700-a781-11e8-9310-cc6624fa7da1.png)

Regards

**Comment by dbousque** [comment]
This pattern is fairly easy to learn, just train more and potentially create an open gazette :)
