### ISSUE TITLE
RecastAI does not match entities from conversation text that matched days before.

### ISSUE THREAD

**Issue by mellisdesigns** [RecastAI/Recast.AI#8]
Hey Guys

I have been working on a bot, and my entities have been coming through nicely. I tried tonight and now I am not getting any matched entities. The testing text has not changed at all.

![image](https://cloud.githubusercontent.com/assets/629570/26061476/9cef9330-39ba-11e7-8ece-ffba7e3ab06a.png)

![image](https://cloud.githubusercontent.com/assets/629570/26061500/b262fd74-39ba-11e7-8adf-4c8e336e7983.png)

The above response from recast would have given me entities result with a length of 1.

Has anything changed drastically in the last week on how the message request is processed? 

Cheers

**Comment by PaulRenvoise** [comment]
Hi,
Can you provide you user name and bot name please ?

**Comment by mellisdesigns** [comment]
Hey,

My RecastAI username is mellisdesigns and my bots name is boganbruce

Cheers, let me know if you need anything else.


On May 15, 2017 10:59 PM, "Paul" <notifications@github.com> wrote:

Hi,
Can you provide you user name and bot name please ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RecastAI/Recast.AI/issues/8#issuecomment-301501610>,
or mute
the thread

**Comment by PaulRenvoise** [comment]
Thanks!
Now can you provide a sentence that was working before and is no longer working please?

**Comment by mellisdesigns** [comment]
So my bot would recognise the raw conversation message 'Tram' and give me
the 'transport_type' entity as 'tram' in the response.

**Comment by PaulRenvoise** [comment]
Hi,
Looks like you encountered an issue with the training scheduler, everything is should be working now, can you confirm?

**Comment by mellisdesigns** [comment]
Hey, just confirmed that my deployed version of the bot which was not
working, is now picking up the correct entity! Cheers guys, everything is
working correctly. Is the Training Scheduler something in my control?

**Comment by PaulRenvoise** [comment]
Unfortunately not, but you can see when a training is running on the top-right corner of the platform! :)
