### ISSUE TITLE
Facebook messenger connector language

### ISSUE THREAD

**Issue by tattoodobem** [RecastAI/Recast.AI#80]
i created a connector for Messenger.
My bot default language is portuguese, but if i send a message in Portuguese it arrives as uk and it fails to recognize. 
How can i change the language the connector uses?

**Comment by maudnals** [comment]
Hi @tattoodobem,
Normally, the connector shouldn't impact the way language detection works.  
Have you tried having the exact same conversation with your bot, from the Recast.AI platform? Just so we can isolate the problem. 
You might want to hit the "TEST" button and see what language is detected. Use the toggle "JSON view / Smart view" for more details.

**Comment by dbousque** [comment]
Hi @tattoodobem, the language of your conversation is fixed, you use 'change_language' actions in your bot-builder. In your specific case, you can restart the conversation with your bot on Messenger by removing it and starting again (settings wheel in the top right on Messenger).

**Comment by tattoodobem** [comment]
i think the problem is the connector has a language flag, i made a connector myself with the language as pt and it worked alright. with you connector i receveid messages as uk (i saw it in monitor)

**Comment by tattoodobem** [comment]
same happens in telegram. deleted my previous telegram bot. built it again. Still in english.
