### ISSUE TITLE
Will confidence level be increased automatically with repeated chat and reply?

### ISSUE THREAD

**Issue by jasonxia2018** [RecastAI/Recast.AI#86]
I observed that the confidence level for the determination of reply for an intent was increased after I have tested the intent for some times. I'm not quite sure if the confidence level change was caused by my accident change on training data for the intent. So I'm asking if it can be increased automatically.

**Comment by dbousque** [comment]
Hi @jasonxia2018 , the confidence is a metric telling you how confident the NLP model is that the intent/entity was correctly recognized. Because your model becomes better as you train it (add more expressions, create custom entities and gazettes etc.), the recognition confidence will tend to grow.
