### ISSUE TITLE
blank page in test mode

### ISSUE THREAD

**Issue by yimialejoh** [RecastAI/Recast.AI#90]
Hi, I'm trying my bot in "Test your bot" option, and when I call a webhook that sends a quick response type of message, the page goes blank. The webhook sent the quick response message correctly.

![image](https://user-images.githubusercontent.com/38698937/47110182-bf464600-d215-11e8-9be4-17141ba1e383.png)

and then

![image](https://user-images.githubusercontent.com/38698937/47110268-f6b4f280-d215-11e8-9d62-28fa4952c578.png)

**Comment by yimialejoh** [comment]
if I do it on the web channel, it works fine.

![image](https://user-images.githubusercontent.com/38698937/47111495-5365dc80-d219-11e8-9031-8203fd661c05.png)

**Comment by aurelie-lamy** [comment]
Hi @yimialejoh, we are on it, thanks for your feedback.

**Comment by yimialejoh** [comment]
hi @aurelie-lamy we found the bug, 
The problem occurs  when I redirect to other skill and it shows a card messages like quick reply or carousel.

This is a public test bot in case you want to try it.
https://recast.ai/yherrera/testerror

**Comment by aurelie-lamy** [comment]
Hi @yimialejoh we fixed it, so it works now 👍
