### ISSUE TITLE
Delete a message group

### ISSUE THREAD

**Issue by yimialejoh** [RecastAI/Recast.AI#91]
Hello,

Today I tried to delete a Message group in bot builder, but does not work:
I Used chrome and firefox.

![image](https://user-images.githubusercontent.com/38698937/47156027-c28c1100-d2ab-11e8-8a6b-43a6802eae82.png)

**Comment by aurelie-lamy** [comment]
Hi @yimialejoh we fixed the bug, you can now delete action group :)
