### ISSUE TITLE
Unable to detect multiple skills from single utterance 

### ISSUE THREAD

**Issue by poohsasne** [RecastAI/Recast.AI#94]
I've multiple skills, and I've provided multiple utterances matching to each skill, but i tried writing one utterance which is combination of 2 skills, and i tested that, but it is returning me as a single skill. I'm interested in getting multiple skills.
Can you suggest me to achieve this scenario? please provide the best way

**Comment by plieb** [comment]
It is not possible to trigger multiple skill at the same time, else the bot builder will fallback
