### ISSUE TITLE
Bot stucked on trainning mode - wont update

### ISSUE THREAD

**Issue by SofiaPe** [RecastAI/Recast.AI#96]
I clicked on my bot's trainnig button to update it's info, yet it is stucked on it. It has been charging for about fifteen minutes now and wont update. Also, I was using it on the automatic trainning option, yet since yesterday it changed to manual trainning and wont let me change it back. What can I do?

![train](https://user-images.githubusercontent.com/44376168/47657318-d0b91780-db5e-11e8-9064-ff86497ccf62.PNG)

![train 2](https://user-images.githubusercontent.com/44376168/47657308-cac33680-db5e-11e8-98ca-52e72a0b510b.PNG)

**Comment by aurelie-lamy** [comment]
Hi @SofiaPe , the train of your bot needs to be finished now, can you confirm it please?
I have opened a ticket to our technical support to improve it (SAPMLCONV-771)

**Comment by SofiaPe** [comment]
Hi @aurelie-lamy the trainning works now, but only on manual mode, it still wont let me change to automatic.

**Comment by aurelie-lamy** [comment]
Hi @SofiaPe, how many expressions and intents do you have in your bot?

**Comment by SofiaPe** [comment]
I have 48 intents and about 20 expressions or more each.

**Comment by aurelie-lamy** [comment]
Hi @SofiaPe if your bot has more than 30 intents or 10 000 sentences, you can't change to automatic mode.
