### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by yimialejoh** [RecastAI/Recast.AI#99]
Hi, 
we enable the bot's versioning, but when creating a new one, we see that it did not copy the build tab.

![imagen](https://user-images.githubusercontent.com/38698937/47724345-7c786b00-dc24-11e8-98c8-309cd0d9638b.png)

thank you very much for the help

regards.

**Comment by yimialejoh** [comment]
hi @aurelie-lamy, ok:

1. Enable the versioning:
![imagen](https://user-images.githubusercontent.com/38698937/47725470-9f0b8380-dc26-11e8-80f1-14ec4857e830.png)

2. Create a new version:
![imagen](https://user-images.githubusercontent.com/38698937/47725650-e8f46980-dc26-11e8-8ee8-80e26462823f.png)

3. Create a new environment for the new version:
![imagen](https://user-images.githubusercontent.com/38698937/47725708-075a6500-dc27-11e8-9d96-620616f36aa5.png)

4. Test (The build tab were not copy)

![imagen](https://user-images.githubusercontent.com/38698937/47725869-5a341c80-dc27-11e8-9385-ebe4ea4d0e99.png)

**Comment by aurelie-lamy** [comment]
Thanks @yimialejoh , we are on it.

**Comment by aurelie-lamy** [comment]
@yimialejoh we fixed it! many thanks for your feedback
